[package]
name = "noita_api"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
libloading = "0.8.5"
noita_api_macro = {path = "../noita_api_macro"}
shared = {path = "../../shared"}
strum = "0.26.3"
base64 = "0.22.1"