[workspace]
members = ["tangled"]

[package]
name = "noita-proxy"
version = "0.8.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.21.0"
eframe = { version="0.27.2", features = ["persistence", "glow", "default_fonts"], default_features = false }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"
tangled = { path = "tangled" }
serde = { version = "1.0.199", features = ["serde_derive", "derive"] }
bitcode = "0.6.0"
lz4_flex = { version = "0.11.3", default_features = false, features = ["std"]}
rand = "0.8.5"
steamworks = "0.11.0"
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
clipboard = "0.5.0"
socket2 = { version = "0.5.7", features = ["all"] }
egui-file-dialog = "0.5.0"
reqwest = { version = "0.12.4", features = ["blocking", "json"] }
serde_json = "1.0.117"
thiserror = "1.0.61"
poll-promise = "0.3.0"
zip = "1.3.1"
self-replace = "1.3.7"
image = { version = "0.25.1", default_features = false, features = ["png"] }
egui_extras = { version = "*", features = ["all_loaders"] }
bytemuck = { version = "1.16.0", features = ["derive"] }
bincode = "1.3.3"
rustc-hash = "1.1.0"

[profile.dev]
opt-level = 1

[profile.release]
lto = "thin"

[profile.release-debug]
inherits = "release"
debug = true
lto = false
