[package]
name = "ewext"
version = "0.4.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]


[profile.release]
lto = true
strip = true # Not having that causes wine debugger to crash.
panic = "abort"

[dependencies]
backtrace = "0.3.74"
iced-x86 = "1.21.0"
noita_api_macro = {path = "noita_api_macro"}
eyre = "0.6.12"
noita_api = {path = "noita_api"}
shared = {path = "../shared"}

[features]
#enables cross-compilation on older systems (for example, when compiling on ubuntu 20.04)
#due to unresolved bug in rust toolchain
#https://github.com/rust-lang/rust/issues/79609
pre2204 = []
